@MultiTenancy_HostAddress = https://localhost:7271

GET {{MultiTenancy_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{MultiTenancy_HostAddress}}/api/products
Content-Type: application/json

{
  //CreateProductDto
}

###

GET {{MultiTenancy_HostAddress}}/api/products
tenant:company1
###

GET {{MultiTenancy_HostAddress}}/api/products

###

POST {{MultiTenancy_HostAddress}}/api/products
Content-Type: application/json
tenant:company1

  {
    "id": 5,
    "name": "co1",
    "description": "co1",
    "rate": 42
  }

###
